Forms
KatIsCoding/BlogApp pull request #6
Opened 2022-02-11 20:20 UTC by KatIsCoding

In this update, forms for creating new posts, new comments to those posts and liking posts have been added

2022-02-11 21:06 UTC, oloomoses requested changes
Hi @KatIsCoding, 


Great job on the linter configuration and the readme file. 
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

_Slack: Oloo Moses_
------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-11 21:06 UTC, oloomoses commented on app/controllers/posts_controller.rb
> +
- [ ] Kindly add a `new` method for instantiating a new post.

2022-02-11 21:06 UTC, oloomoses commented on app/controllers/posts_controller.rb
> +  end
- [ ] To create a new post, it is a requirement that you use strong params. Kindly read about strong params [here](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/lessons/Controllers_lesson.md#:~:text=Pay%20special%20attention%20to%20the%20strong%20parameters%20description%20in%20Rails%20Guides)
- [ ] Kindly use the current user to create a new post. the code should look like below.
```ruby
   def create
      @post = @current_user.posts.new(post_params)

      respond_to do |format|
        if @post.save
          format.html { redirect_to @post }
        else
          format.html { render :new }
        end
      end
    end
```

2022-02-11 21:06 UTC, oloomoses commented on app/controllers/posts_controller.rb
> +  end
- [ ] Creating a new comment should be done in the `comments_controller`. Kindly create one and add `new` and `create` methods. The methods should look like below:
```ruby
                              def create
    @comment = @current_user.comments.new(params)
                      @comment.post_id = params[:post_id]

                                    if @comment.save
      redirect_to                                           post_                          path(@comment.post)
    else
      @article = Post.find(params[:post_id])
                                                                                           redirect_to post_path(@post)
    end
  end
```

2022-02-11 21:06 UTC, oloomoses commented on app/controllers/posts_controller.rb
> +  end
- [ ] Creating a new like should be done in the `likes_controller`. Kindly create one and add `new` and `create` methods. The methods should look like below:
```ruby
                              def create
    @like = @current_user.comments.new(params)
                      @comment.post_id = params[:post_id]

                                    if @comment.save
      redirect_to                                           post_                          path(@comment.post)
    else
      @article = Post.find(params[:post_id])
                                                                                           redirect_to post_path(@post)
    end
  end
```

2022-02-11 21:06 UTC, oloomoses commented on app/views/posts/show.html.erb
>  </div>
- [ ] The new post form should be in `views/posts/new.html.erb`.
- [ ] Kindly ensure that a user can create a post, add comments, and a like.

2022-02-11 21:06 UTC, oloomoses commented on config/routes.rb
> +  post '/like/:id', to: 'posts#add_like'
- [ ] Kindly update the routes for creating likes and comments accordingly

2022-02-12 03:47 UTC, arslanbisharat approved these changes
# Approved 👏 

Hi there, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

To Highlight: 
- The Pull Request has a proper title and description. ✔️ 
- You have added a descriptive Readme file. Good Job. ✔️ 
- There is no linter error is present. ✔️ 
- Project has met all the technical aspects you needed for this project. Keep rocking! ✔️ 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of code reviews per project which you can see from your dashboard. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)_

2022-02-21 19:38 UTC, merged